/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import rojerusan.RSTableMetro;

/**
 *
 * @author isaac
 */
public class detallesVenta extends javax.swing.JPanel{

    /**
     * Creates new form confiteria
     */

    public detallesVenta() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtComentario1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidos = new rojerusan.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        marcar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOrden = new javax.swing.JTextArea();

        txtComentario1.setBackground(new java.awt.Color(238, 238, 238));
        txtComentario1.setColumns(20);
        txtComentario1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtComentario1.setForeground(new java.awt.Color(0, 0, 0));
        txtComentario1.setRows(5);
        txtComentario1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Comentarios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("MADE Soulmaze", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 44, 82));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Detalles Pedidos Royal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tablaPedidos.setBackground(new java.awt.Color(255, 255, 255));
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.ª ", "Tarjeta", "Pago", "Precio", "Sala", "Silla", "Cliente", "Mecero", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPedidos.setAltoHead(36);
        tablaPedidos.setColorBackgoundHead(new java.awt.Color(9, 76, 123));
        tablaPedidos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tablaPedidos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tablaPedidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablaPedidos.setFuenteFilas(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablaPedidos.setFuenteFilasSelect(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tablaPedidos.setFuenteHead(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tablaPedidos.setRowHeight(32);
        jScrollPane2.setViewportView(tablaPedidos);
        tablaPedidos.getAccessibleContext().setAccessibleName("");
        tablaPedidos.getAccessibleContext().setAccessibleDescription("");

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Orden", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jScrollPane1.setBorder(null);

        txtComentario.setBackground(new java.awt.Color(238, 238, 238));
        txtComentario.setColumns(20);
        txtComentario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtComentario.setForeground(new java.awt.Color(0, 0, 0));
        txtComentario.setRows(5);
        txtComentario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Comentarios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jScrollPane1.setViewportView(txtComentario);

        marcar.setBackground(new java.awt.Color(9, 76, 123));
        marcar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        marcar.setForeground(new java.awt.Color(255, 255, 255));
        marcar.setText("Marcar");
        marcar.setBorderPainted(false);
        marcar.setFocusPainted(false);
        marcar.setFocusable(false);
        marcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        txtOrden.setBackground(new java.awt.Color(238, 238, 238));
        txtOrden.setColumns(20);
        txtOrden.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtOrden.setForeground(new java.awt.Color(0, 0, 0));
        txtOrden.setRows(5);
        txtOrden.setBorder(null);
        jScrollPane3.setViewportView(txtOrden);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marcar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(marcar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 325, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void marcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JButton marcar;
    public rojerusan.RSTableMetro tablaPedidos;
    public javax.swing.JTextArea txtComentario;
    public javax.swing.JTextArea txtComentario1;
    public javax.swing.JTextArea txtOrden;
    // End of variables declaration//GEN-END:variables
}
